---
apiVersion: v1
kind: Service
metadata:
  name: ar-validation
  namespace: ar-sandbox
  labels:
    app: ar-validation
spec:
  type: ClusterIP
  selector:
    app: ar-validation
    replica: blue
  ports:
    - name: http
      port: 80
      targetPort: 8084
      protocol: TCP
