name: CI/CD workflow for Gradle Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sonar_status: ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}
      sonar_analysis_id: ${{ steps.sonarqube-scan.outputs.sonar_analysis_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "11"
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build --scan
      - name: SonarQube scan
        id: sonarqube-scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=VijayakumarZura
            -Dsonar.projectKey=VijayakumarZura_ar-validation_2a6bb681-8355-4fe8-b8d3-d475ac402b1c
            -Dsonar.java.binaries=build/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        if: always()
      - name: Print SonarQube Quality Gate Status
        run: echo "The Quality Gate status is ${{
          steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}."
  send_email_notification:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Fetch SonarQube Analysis Results
        id: fetch-sonarqube-results
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ANALYSIS_ID=${{ needs.build.outputs.sonar_analysis_id }}
          curl -u $SONAR_TOKEN: -s "$SONAR_HOST_URL/api/qualitygates/project_status?analysisId=$ANALYSIS_ID" -o sonar_results.json
          SONAR_RESULTS=$(jq -r .projectStatus.status < sonar_results.json)
          echo "SonarQube Results: $SONAR_RESULTS"
          echo "SONAR_RESULTS=$SONAR_RESULTS" >> $GITHUB_ENV
      - name: Send email via Microsoft Graph
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          EMAIL_RECIPIENTS: vari@zuralabs.com
          EMAIL_FROM: vari@zuralabs.com
          SONAR_RESULTS: ${{ env.SONAR_RESULTS }}
        run: |
          curl -X POST "https://login.microsoftonline.com/$AZURE_TENANT_ID/oauth2/v2.0/token" \
            -F grant_type=client_credentials \
            -F client_id="$AZURE_CLIENT_ID" \
            -F client_secret="$AZURE_CLIENT_SECRET" \
            -F scope="https://graph.microsoft.com/.default" \
            -o token.json

          ACCESS_TOKEN=$(jq -r .access_token < token.json)

          GRADLE_BUILD_STATUS="${{ needs.build.result }}"
          SONARQUBE_STATUS="${{ needs.build.outputs.sonar_status }}"

          echo "Build result: $GRADLE_BUILD_STATUS"
          echo "SonarQube result: $SONARQUBE_STATUS"

          if [[ "$GRADLE_BUILD_STATUS" == "success" && "$SONARQUBE_STATUS" == "PASSED" ]]; then
            STATUS="The SonarQube analysis passed successfully."
          else
            STATUS="The SonarQube analysis failed or the quality gate was not passed."
          fi

          IFS=',' read -ra RECIPIENTS <<< "$EMAIL_RECIPIENTS"

          RECIPIENTS_JSON=$(for email in "${RECIPIENTS[@]}"; do printf '{"emailAddress": {"address": "%s"}},' "$email"; done | sed 's/,$//')

          curl -X POST "https://graph.microsoft.com/v1.0/users/$EMAIL_FROM/sendMail" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "message": {
                "subject": "GitHub Action Notification - SonarQube Result",
                "body": {
                  "contentType": "Text",
                  "content": "The GitHub Action workflow has completed. \n\nBuild status: '"$GRADLE_BUILD_STATUS"'. \n\nSonarQube status: '"$STATUS"' \n\nSonarQube Results: '"$SONAR_RESULTS"'"
                },
                "toRecipients": ['"$RECIPIENTS_JSON"']
              }
            }'
